services:
  app:
    env_file:
      - "${ENV_FILE_NAME}"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV_FILE_NAME: "${ENV_FILE_NAME}"
    volumes:
      - .:/app
    ports:
      - "${UVICORN__PORT}:${UVICORN__PORT}"
  
  db:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=${POSTGRESQL__USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL__PASSWORD}
      - POSTGRES_DB=${POSTGRESQL__DATABASE}
    ports:
      - "${POSTGRESQL__PORT}:${POSTGRESQL__PORT}"
    volumes:
      - vardast-db-volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

volumes:
  vardast-db-volume: